# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('imdb_score', models.FloatField()),
                ('popularity_99', models.FloatField()),
                ('director', models.CharField(max_length=200)),
                ('image', models.URLField(max_length=300)),
                ('genres', models.ManyToManyField(related_name='movies', to='movieapi.Genre')),
            ],
        ),
    ]
