# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-26 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
